apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ojf6vlzoo-go
  janus-idp.io/tekton: ojf6vlzoo-go
  backstage.io/kubernetes-id: ojf6vlzoo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ojf6vlzoo-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
